<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>Logger</AssemblyName>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
	</ItemGroup>
</Project>
